import { Vec3, Vec4 } from '@axrone/numeric';
import { Transform } from '@axrone/ecs-runtime';
import { Component } from '@axrone/ecs-runtime';
import { script } from '@axrone/ecs-runtime';

export type TrailTextureMode = 'stretch' | 'tile';
export type TrailAlignment = 'view' | 'transform-z' | 'local';

export interface TrailRendererGradientStop {
    readonly position: number;
    readonly color: Vec4 | readonly [number, number, number, number];
}

export interface TrailRendererConfig {
    readonly lifetime?: number;
    readonly minVertexDistance?: number;
    readonly startWidth?: number;
    readonly endWidth?: number;
    readonly widthCurve?: readonly number[];
    readonly colorGradient?: readonly TrailRendererGradientStop[];
    readonly textureMode?: TrailTextureMode;
    readonly alignment?: TrailAlignment;
    readonly textureScale?: readonly [number, number];
    readonly shadowCasting?: boolean;
    readonly generateLightingData?: boolean;
    readonly cornerVertices?: number;
    readonly endCapVertices?: number;
    readonly autodestruct?: boolean;
}

const DEFAULT_GRADIENT: readonly TrailRendererGradientStop[] = Object.freeze([
    { position: 0, color: [1, 1, 1, 1] },
    { position: 1, color: [1, 1, 1, 0] },
]);

const toVec4 = (
    value?: Vec4 | readonly [number, number, number, number],
    fallback: Vec4 = Vec4.ONE
): Vec4 => {
    if (value instanceof Vec4) {
        return Vec4.from(value);
    }

    if (Array.isArray(value) && value.length === 4) {
        return Vec4.fromArray(value);
    }

    return fallback.clone();
};

interface TrailPoint {
    position: Vec3;
    time: number;
    width: number;
}

/**
 * TrailRenderer component creates a trailing effect behind moving objects.
 * The trail is generated by sampling the object's position over time and
 * creating a ribbon-like mesh that fades over its lifetime.
 *
 * @example
 * ```ts
 * const trail = new TrailRenderer({
 *     lifetime: 1.5,
 *     startWidth: 0.5,
 *     endWidth: 0,
 * });
 * actor.addComponent(TrailRenderer, trail);
 * ```
 */
@script({
    scriptName: 'TrailRenderer',
    priority: 150,
    executeInEditMode: false,
    singleton: false,
})
export class TrailRenderer extends Component {
    private _lifetime: number;
    private _minVertexDistance: number;
    private _startWidth: number;
    private _endWidth: number;
    private _widthCurve: number[];
    private _colorGradient: TrailRendererGradientStop[];
    private _textureMode: TrailTextureMode;
    private _alignment: TrailAlignment;
    private _textureScaleX: number;
    private _textureScaleY: number;
    private _shadowCasting: boolean;
    private _generateLightingData: boolean;
    private _cornerVertices: number;
    private _endCapVertices: number;
    private _autodestruct: boolean;

    private readonly _points: TrailPoint[] = [];
    private _lastPosition: Vec3 | null = null;
    private _elapsedTime: number = 0;

    constructor(config: TrailRendererConfig = {}) {
        super();
        this._lifetime = 1;
        this._minVertexDistance = 0.1;
        this._startWidth = 1;
        this._endWidth = 1;
        this._widthCurve = [];
        this._colorGradient = [...DEFAULT_GRADIENT];
        this._textureMode = 'stretch';
        this._alignment = 'view';
        this._textureScaleX = 1;
        this._textureScaleY = 1;
        this._shadowCasting = false;
        this._generateLightingData = false;
        this._cornerVertices = 0;
        this._endCapVertices = 0;
        this._autodestruct = false;
        this._applyConfig(config);
    }

    get lifetime(): number {
        return this._lifetime;
    }

    set lifetime(value: number) {
        this._lifetime = Math.max(0.001, value);
    }

    get minVertexDistance(): number {
        return this._minVertexDistance;
    }

    set minVertexDistance(value: number) {
        this._minVertexDistance = Math.max(0.001, value);
    }

    get startWidth(): number {
        return this._startWidth;
    }

    set startWidth(value: number) {
        this._startWidth = Math.max(0, value);
    }

    get endWidth(): number {
        return this._endWidth;
    }

    set endWidth(value: number) {
        this._endWidth = Math.max(0, value);
    }

    get widthCurve(): readonly number[] {
        return this._widthCurve;
    }

    set widthCurve(value: readonly number[]) {
        this._widthCurve = [...value];
    }

    get colorGradient(): readonly TrailRendererGradientStop[] {
        return this._colorGradient;
    }

    set colorGradient(value: readonly TrailRendererGradientStop[]) {
        this._colorGradient = value.map((stop) => ({
            position: Math.max(0, Math.min(1, stop.position)),
            color: toVec4(stop.color),
        }));
    }

    get textureMode(): TrailTextureMode {
        return this._textureMode;
    }

    set textureMode(value: TrailTextureMode) {
        this._textureMode = value;
    }

    get alignment(): TrailAlignment {
        return this._alignment;
    }

    set alignment(value: TrailAlignment) {
        this._alignment = value;
    }

    get textureScale(): readonly [number, number] {
        return [this._textureScaleX, this._textureScaleY];
    }

    set textureScale(value: readonly [number, number]) {
        this._textureScaleX = value[0];
        this._textureScaleY = value[1];
    }

    get shadowCasting(): boolean {
        return this._shadowCasting;
    }

    set shadowCasting(value: boolean) {
        this._shadowCasting = value;
    }

    get generateLightingData(): boolean {
        return this._generateLightingData;
    }

    set generateLightingData(value: boolean) {
        this._generateLightingData = value;
    }

    get cornerVertices(): number {
        return this._cornerVertices;
    }

    set cornerVertices(value: number) {
        this._cornerVertices = Math.max(0, Math.floor(value));
    }

    get endCapVertices(): number {
        return this._endCapVertices;
    }

    set endCapVertices(value: number) {
        this._endCapVertices = Math.max(0, Math.floor(value));
    }

    get autodestruct(): boolean {
        return this._autodestruct;
    }

    set autodestruct(value: boolean) {
        this._autodestruct = value;
    }

    get pointCount(): number {
        return this._points.length;
    }

    /**
     * Clears all trail points immediately.
     */
    clear(): void {
        this._points.length = 0;
        this._lastPosition = null;
    }

    /**
     * Evaluates the width at a normalized position (0-1) along the trail.
     */
    evaluateWidth(t: number): number {
        const clampedT = Math.max(0, Math.min(1, t));

        if (this._widthCurve.length >= 2) {
            const curveT = clampedT * (this._widthCurve.length - 1);
            const index = Math.floor(curveT);
            const fraction = curveT - index;
            const a = this._widthCurve[index] ?? 1;
            const b = this._widthCurve[Math.min(index + 1, this._widthCurve.length - 1)] ?? 1;
            const curveValue = a + (b - a) * fraction;
            return this._startWidth + (this._endWidth - this._startWidth) * curveValue;
        }

        return this._startWidth + (this._endWidth - this._startWidth) * clampedT;
    }

    /**
     * Evaluates the color at a normalized position (0-1) along the trail.
     */
    evaluateColor(t: number): Vec4 {
        const clampedT = Math.max(0, Math.min(1, t));

        if (this._colorGradient.length === 0) {
            return Vec4.ONE.clone();
        }

        if (this._colorGradient.length === 1) {
            return toVec4(this._colorGradient[0].color);
        }

        let lowerStop = this._colorGradient[0];
        let upperStop = this._colorGradient[this._colorGradient.length - 1];

        for (let i = 0; i < this._colorGradient.length - 1; i++) {
            const current = this._colorGradient[i];
            const next = this._colorGradient[i + 1];
            if (current && next && clampedT >= current.position && clampedT <= next.position) {
                lowerStop = current;
                upperStop = next;
                break;
            }
        }

        const range = upperStop.position - lowerStop.position;
        const fraction = range > 0 ? (clampedT - lowerStop.position) / range : 0;

        const lowerColor = toVec4(lowerStop.color);
        const upperColor = toVec4(upperStop.color);

        return new Vec4(
            lowerColor.x + (upperColor.x - lowerColor.x) * fraction,
            lowerColor.y + (upperColor.y - lowerColor.y) * fraction,
            lowerColor.z + (upperColor.z - lowerColor.z) * fraction,
            lowerColor.w + (upperColor.w - lowerColor.w) * fraction
        );
    }

    /**
     * Gets all current trail points for rendering.
     */
    getPoints(): readonly TrailPoint[] {
        return this._points;
    }

    override update(deltaTime: number): void {
        this._elapsedTime += deltaTime;

        const transform = this.transform as Transform | undefined;
        if (!transform) {
            return;
        }

        const currentPosition = transform.worldPosition;

        if (!this._lastPosition) {
            this._lastPosition = currentPosition.clone();
            this._points.push({
                position: currentPosition.clone(),
                time: this._elapsedTime,
                width: this._startWidth,
            });
            return;
        }

        const distance = Vec3.distance(currentPosition, this._lastPosition);

        if (distance >= this._minVertexDistance) {
            this._points.push({
                position: currentPosition.clone(),
                time: this._elapsedTime,
                width: this._startWidth,
            });
            this._lastPosition = currentPosition.clone();
        }

        this._pruneExpiredPoints();
    }

    override serialize(): Record<string, unknown> {
        return {
            lifetime: this._lifetime,
            minVertexDistance: this._minVertexDistance,
            startWidth: this._startWidth,
            endWidth: this._endWidth,
            widthCurve: [...this._widthCurve],
            colorGradient: this._colorGradient.map((stop) => {
                const color = toVec4(stop.color);
                return {
                    position: stop.position,
                    color: [color.x, color.y, color.z, color.w],
                };
            }),
            textureMode: this._textureMode,
            alignment: this._alignment,
            textureScale: [this._textureScaleX, this._textureScaleY],
            shadowCasting: this._shadowCasting,
            generateLightingData: this._generateLightingData,
            cornerVertices: this._cornerVertices,
            endCapVertices: this._endCapVertices,
            autodestruct: this._autodestruct,
        };
    }

    override deserialize(data: Record<string, any>): void {
        const patch: TrailRendererConfig = {};

        if (typeof data.lifetime === 'number') {
            (patch as any).lifetime = data.lifetime;
        }
        if (typeof data.minVertexDistance === 'number') {
            (patch as any).minVertexDistance = data.minVertexDistance;
        }
        if (typeof data.startWidth === 'number') {
            (patch as any).startWidth = data.startWidth;
        }
        if (typeof data.endWidth === 'number') {
            (patch as any).endWidth = data.endWidth;
        }
        if (Array.isArray(data.widthCurve)) {
            (patch as any).widthCurve = data.widthCurve;
        }
        if (Array.isArray(data.colorGradient)) {
            (patch as any).colorGradient = data.colorGradient;
        }
        if (typeof data.textureMode === 'string') {
            (patch as any).textureMode = data.textureMode;
        }
        if (typeof data.alignment === 'string') {
            (patch as any).alignment = data.alignment;
        }
        if (Array.isArray(data.textureScale) && data.textureScale.length === 2) {
            (patch as any).textureScale = data.textureScale;
        }
        if (typeof data.shadowCasting === 'boolean') {
            (patch as any).shadowCasting = data.shadowCasting;
        }
        if (typeof data.generateLightingData === 'boolean') {
            (patch as any).generateLightingData = data.generateLightingData;
        }
        if (typeof data.cornerVertices === 'number') {
            (patch as any).cornerVertices = data.cornerVertices;
        }
        if (typeof data.endCapVertices === 'number') {
            (patch as any).endCapVertices = data.endCapVertices;
        }
        if (typeof data.autodestruct === 'boolean') {
            (patch as any).autodestruct = data.autodestruct;
        }

        this._applyConfig(patch);
    }

    private _pruneExpiredPoints(): void {
        const cutoffTime = this._elapsedTime - this._lifetime;

        while (this._points.length > 0 && this._points[0]!.time < cutoffTime) {
            this._points.shift();
        }
    }

    private _applyConfig(config: TrailRendererConfig): void {
        if (typeof config.lifetime === 'number') {
            this._lifetime = Math.max(0.001, config.lifetime);
        }
        if (typeof config.minVertexDistance === 'number') {
            this._minVertexDistance = Math.max(0.001, config.minVertexDistance);
        }
        if (typeof config.startWidth === 'number') {
            this._startWidth = Math.max(0, config.startWidth);
        }
        if (typeof config.endWidth === 'number') {
            this._endWidth = Math.max(0, config.endWidth);
        }
        if (config.widthCurve) {
            this._widthCurve = [...config.widthCurve];
        }
        if (config.colorGradient) {
            this._colorGradient = config.colorGradient.map((stop) => ({
                position: Math.max(0, Math.min(1, stop.position)),
                color: toVec4(stop.color),
            }));
        }
        if (config.textureMode) {
            this._textureMode = config.textureMode;
        }
        if (config.alignment) {
            this._alignment = config.alignment;
        }
        if (config.textureScale) {
            this._textureScaleX = config.textureScale[0];
            this._textureScaleY = config.textureScale[1];
        }
        if (typeof config.shadowCasting === 'boolean') {
            this._shadowCasting = config.shadowCasting;
        }
        if (typeof config.generateLightingData === 'boolean') {
            this._generateLightingData = config.generateLightingData;
        }
        if (typeof config.cornerVertices === 'number') {
            this._cornerVertices = Math.max(0, Math.floor(config.cornerVertices));
        }
        if (typeof config.endCapVertices === 'number') {
            this._endCapVertices = Math.max(0, Math.floor(config.endCapVertices));
        }
        if (typeof config.autodestruct === 'boolean') {
            this._autodestruct = config.autodestruct;
        }
    }
}
