import { Vec3, Vec4 } from '@axrone/numeric';
import { Transform } from '@axrone/ecs-runtime';
import { Component } from '@axrone/ecs-runtime';
import { script } from '@axrone/ecs-runtime';

export type TrailTextureMode = 'stretch' | 'tile';
export type TrailAlignment = 'view' | 'transform-z' | 'local';

export interface TrailRendererGradientStop {
    readonly position: number;
    readonly color: Vec4 | readonly [number, number, number, number];
}

export interface TrailRendererConfig {
    readonly lifetime?: number;
    readonly minVertexDistance?: number;
    readonly startWidth?: number;
    readonly endWidth?: number;
    readonly widthCurve?: readonly number[];
    readonly colorGradient?: readonly TrailRendererGradientStop[];
    readonly textureMode?: TrailTextureMode;
    readonly alignment?: TrailAlignment;
    readonly textureScale?: readonly [number, number];
    readonly shadowCasting?: boolean;
    readonly generateLightingData?: boolean;
    readonly cornerVertices?: number;
    readonly endCapVertices?: number;
    readonly autodestruct?: boolean;
}

/** Mutable projection of TrailRendererConfig — avoids `(patch as any)` bypasses. */
type MutableTrailConfig = { -readonly [K in keyof TrailRendererConfig]: TrailRendererConfig[K] };

const DEFAULT_GRADIENT: readonly TrailRendererGradientStop[] = Object.freeze([
    { position: 0, color: [1, 1, 1, 1] },
    { position: 1, color: [1, 1, 1, 0] },
]);

/** Default ring-buffer capacity for trail points. */
const DEFAULT_MAX_POINTS = 256;

const toVec4 = (
    value?: Vec4 | readonly [number, number, number, number],
    fallback: Vec4 = Vec4.ONE
): Vec4 => {
    if (value instanceof Vec4) {
        return Vec4.from(value);
    }

    if (Array.isArray(value) && value.length === 4) {
        return Vec4.fromArray(value);
    }

    return fallback.clone();
};

/**
 * Writes the components of `value` into `target` without allocating.
 * Used on hot paths where `toVec4` would otherwise create a new Vec4.
 */
const copyIntoVec4 = (
    value: Vec4 | readonly [number, number, number, number],
    target: Vec4,
    fallback: Vec4 = Vec4.ONE
): void => {
    if (value instanceof Vec4) {
        target.x = value.x;
        target.y = value.y;
        target.z = value.z;
        target.w = value.w;
    } else if (Array.isArray(value) && value.length === 4) {
        target.x = value[0];
        target.y = value[1];
        target.z = value[2];
        target.w = value[3];
    } else {
        target.x = fallback.x;
        target.y = fallback.y;
        target.z = fallback.z;
        target.w = fallback.w;
    }
};

interface TrailPoint {
    position: Vec3;
    time: number;
    width: number;
}

/**
 * TrailRenderer component creates a trailing effect behind moving objects.
 * The trail is generated by sampling the object's position over time and
 * creating a ribbon-like mesh that fades over its lifetime.
 *
 * @example
 * ```ts
 * const trail = new TrailRenderer({
 *     lifetime: 1.5,
 *     startWidth: 0.5,
 *     endWidth: 0,
 * });
 * actor.addComponent(TrailRenderer, trail);
 * ```
 */
@script({
    scriptName: 'TrailRenderer',
    priority: 150,
    executeInEditMode: false,
    singleton: false,
})
export class TrailRenderer extends Component {
    private _lifetime: number;
    private _minVertexDistance: number;
    private _startWidth: number;
    private _endWidth: number;
    private _widthCurve: number[];
    private _colorGradient: TrailRendererGradientStop[];
    private _textureMode: TrailTextureMode;
    private _alignment: TrailAlignment;
    private _textureScaleX: number;
    private _textureScaleY: number;
    private _shadowCasting: boolean;
    private _generateLightingData: boolean;
    private _cornerVertices: number;
    private _endCapVertices: number;
    private _autodestruct: boolean;

    // ── Ring buffer for trail points (zero-allocation on hot path) ──
    private readonly _capacity: number;
    private readonly _points: TrailPoint[];
    private _headIndex: number = 0;
    private _pointCount: number = 0;

    // ── Pre-allocated temporaries — never re-allocated at runtime ──
    private readonly _tempPosition: Vec3 = new Vec3();
    private readonly _tempColor: Vec4 = new Vec4();
    private readonly _tempLowerColor: Vec4 = new Vec4();
    private readonly _tempUpperColor: Vec4 = new Vec4();
    private readonly _lastPosition: Vec3 = new Vec3();
    private _hasLastPosition: boolean = false;

    private _elapsedTime: number = 0;

    constructor(config: TrailRendererConfig = {}) {
        super();
        this._lifetime = 1;
        this._minVertexDistance = 0.1;
        this._startWidth = 1;
        this._endWidth = 1;
        this._widthCurve = [];
        this._colorGradient = [...DEFAULT_GRADIENT];
        this._textureMode = 'stretch';
        this._alignment = 'view';
        this._textureScaleX = 1;
        this._textureScaleY = 1;
        this._shadowCasting = false;
        this._generateLightingData = false;
        this._cornerVertices = 0;
        this._endCapVertices = 0;
        this._autodestruct = false;

        // Pre-allocate the ring buffer with reusable TrailPoint objects.
        this._capacity = DEFAULT_MAX_POINTS;
        this._points = new Array<TrailPoint>(this._capacity);
        for (let i = 0; i < this._capacity; i++) {
            this._points[i] = { position: new Vec3(), time: 0, width: 0 };
        }

        this._applyConfig(config);
    }

    get lifetime(): number {
        return this._lifetime;
    }

    set lifetime(value: number) {
        this._lifetime = Math.max(0.001, value);
    }

    get minVertexDistance(): number {
        return this._minVertexDistance;
    }

    set minVertexDistance(value: number) {
        this._minVertexDistance = Math.max(0.001, value);
    }

    get startWidth(): number {
        return this._startWidth;
    }

    set startWidth(value: number) {
        this._startWidth = Math.max(0, value);
    }

    get endWidth(): number {
        return this._endWidth;
    }

    set endWidth(value: number) {
        this._endWidth = Math.max(0, value);
    }

    get widthCurve(): readonly number[] {
        return this._widthCurve;
    }

    set widthCurve(value: readonly number[]) {
        this._widthCurve = [...value];
    }

    get colorGradient(): readonly TrailRendererGradientStop[] {
        return this._colorGradient;
    }

    set colorGradient(value: readonly TrailRendererGradientStop[]) {
        this._colorGradient = value.map((stop) => ({
            position: Math.max(0, Math.min(1, stop.position)),
            color: toVec4(stop.color),
        }));
    }

    get textureMode(): TrailTextureMode {
        return this._textureMode;
    }

    set textureMode(value: TrailTextureMode) {
        this._textureMode = value;
    }

    get alignment(): TrailAlignment {
        return this._alignment;
    }

    set alignment(value: TrailAlignment) {
        this._alignment = value;
    }

    get textureScale(): readonly [number, number] {
        return [this._textureScaleX, this._textureScaleY];
    }

    set textureScale(value: readonly [number, number]) {
        this._textureScaleX = value[0];
        this._textureScaleY = value[1];
    }

    get shadowCasting(): boolean {
        return this._shadowCasting;
    }

    set shadowCasting(value: boolean) {
        this._shadowCasting = value;
    }

    get generateLightingData(): boolean {
        return this._generateLightingData;
    }

    set generateLightingData(value: boolean) {
        this._generateLightingData = value;
    }

    get cornerVertices(): number {
        return this._cornerVertices;
    }

    set cornerVertices(value: number) {
        this._cornerVertices = Math.max(0, Math.floor(value));
    }

    get endCapVertices(): number {
        return this._endCapVertices;
    }

    set endCapVertices(value: number) {
        this._endCapVertices = Math.max(0, Math.floor(value));
    }

    get autodestruct(): boolean {
        return this._autodestruct;
    }

    set autodestruct(value: boolean) {
        this._autodestruct = value;
    }

    get pointCount(): number {
        return this._pointCount;
    }

    /**
     * Clears all trail points immediately.
     */
    clear(): void {
        this._headIndex = 0;
        this._pointCount = 0;
        this._hasLastPosition = false;
    }

    /**
     * Evaluates the width at a normalized position (0-1) along the trail.
     */
    evaluateWidth(t: number): number {
        const clampedT = Math.max(0, Math.min(1, t));

        if (this._widthCurve.length >= 2) {
            const curveT = clampedT * (this._widthCurve.length - 1);
            const index = Math.floor(curveT);
            const fraction = curveT - index;
            const a = this._widthCurve[index] ?? 1;
            const b = this._widthCurve[Math.min(index + 1, this._widthCurve.length - 1)] ?? 1;
            const curveValue = a + (b - a) * fraction;
            return this._startWidth + (this._endWidth - this._startWidth) * curveValue;
        }

        return this._startWidth + (this._endWidth - this._startWidth) * clampedT;
    }

    /**
     * Evaluates the color at a normalized position (0-1) along the trail.
     * Zero-allocation: writes into the pre-allocated `_tempColor` Vec4.
     *
     * NOTE: callers that need to retain the result across multiple calls
     * should copy the components before the next invocation.
     */
    evaluateColor(t: number): Vec4 {
        const clampedT = Math.max(0, Math.min(1, t));

        if (this._colorGradient.length === 0) {
            this._tempColor.x = 1;
            this._tempColor.y = 1;
            this._tempColor.z = 1;
            this._tempColor.w = 1;
            return this._tempColor;
        }

        if (this._colorGradient.length === 1) {
            copyIntoVec4(this._colorGradient[0].color, this._tempColor);
            return this._tempColor;
        }

        let lowerStop = this._colorGradient[0];
        let upperStop = this._colorGradient[this._colorGradient.length - 1];

        for (let i = 0; i < this._colorGradient.length - 1; i++) {
            const current = this._colorGradient[i];
            const next = this._colorGradient[i + 1];
            if (current && next && clampedT >= current.position && clampedT <= next.position) {
                lowerStop = current;
                upperStop = next;
                break;
            }
        }

        const range = upperStop.position - lowerStop.position;
        const fraction = range > 0 ? (clampedT - lowerStop.position) / range : 0;

        copyIntoVec4(lowerStop.color, this._tempLowerColor);
        copyIntoVec4(upperStop.color, this._tempUpperColor);

        this._tempColor.x = this._tempLowerColor.x + (this._tempUpperColor.x - this._tempLowerColor.x) * fraction;
        this._tempColor.y = this._tempLowerColor.y + (this._tempUpperColor.y - this._tempLowerColor.y) * fraction;
        this._tempColor.z = this._tempLowerColor.z + (this._tempUpperColor.z - this._tempLowerColor.z) * fraction;
        this._tempColor.w = this._tempLowerColor.w + (this._tempUpperColor.w - this._tempLowerColor.w) * fraction;

        return this._tempColor;
    }

    /**
     * Gets all current trail points for rendering.
     * Builds a contiguous view from the ring buffer.
     */
    getPoints(): readonly TrailPoint[] {
        const result: TrailPoint[] = new Array(this._pointCount);
        for (let i = 0; i < this._pointCount; i++) {
            result[i] = this._points[(this._headIndex + i) % this._capacity]!;
        }
        return result;
    }

    /**
     * Hot-path update — zero allocations.
     * All Vec3/TrailPoint writes go into pre-allocated objects.
     */
    override update(deltaTime: number): void {
        this._elapsedTime += deltaTime;

        const transform = this.transform as Transform | undefined;
        if (!transform) {
            return;
        }

        const currentPosition = transform.worldPosition;

        // Stage position into pre-allocated temp (avoids .clone()).
        this._tempPosition.x = currentPosition.x;
        this._tempPosition.y = currentPosition.y;
        this._tempPosition.z = currentPosition.z;

        if (!this._hasLastPosition) {
            this._lastPosition.x = this._tempPosition.x;
            this._lastPosition.y = this._tempPosition.y;
            this._lastPosition.z = this._tempPosition.z;
            this._hasLastPosition = true;
            this._addPoint(this._tempPosition.x, this._tempPosition.y, this._tempPosition.z, this._elapsedTime, this._startWidth);
            return;
        }

        const dx = this._tempPosition.x - this._lastPosition.x;
        const dy = this._tempPosition.y - this._lastPosition.y;
        const dz = this._tempPosition.z - this._lastPosition.z;
        const distance = Math.sqrt(dx * dx + dy * dy + dz * dz);

        if (distance >= this._minVertexDistance) {
            this._addPoint(this._tempPosition.x, this._tempPosition.y, this._tempPosition.z, this._elapsedTime, this._startWidth);
            this._lastPosition.x = this._tempPosition.x;
            this._lastPosition.y = this._tempPosition.y;
            this._lastPosition.z = this._tempPosition.z;
        }

        this._pruneExpiredPoints();
    }

    override serialize(): Record<string, unknown> {
        return {
            lifetime: this._lifetime,
            minVertexDistance: this._minVertexDistance,
            startWidth: this._startWidth,
            endWidth: this._endWidth,
            widthCurve: [...this._widthCurve],
            colorGradient: this._colorGradient.map((stop) => {
                const color = toVec4(stop.color);
                return {
                    position: stop.position,
                    color: [color.x, color.y, color.z, color.w],
                };
            }),
            textureMode: this._textureMode,
            alignment: this._alignment,
            textureScale: [this._textureScaleX, this._textureScaleY],
            shadowCasting: this._shadowCasting,
            generateLightingData: this._generateLightingData,
            cornerVertices: this._cornerVertices,
            endCapVertices: this._endCapVertices,
            autodestruct: this._autodestruct,
        };
    }

    override deserialize(data: Record<string, any>): void {
        const patch: MutableTrailConfig = {};

        if (typeof data.lifetime === 'number') {
            patch.lifetime = data.lifetime;
        }
        if (typeof data.minVertexDistance === 'number') {
            patch.minVertexDistance = data.minVertexDistance;
        }
        if (typeof data.startWidth === 'number') {
            patch.startWidth = data.startWidth;
        }
        if (typeof data.endWidth === 'number') {
            patch.endWidth = data.endWidth;
        }
        if (Array.isArray(data.widthCurve)) {
            patch.widthCurve = data.widthCurve;
        }
        if (Array.isArray(data.colorGradient)) {
            patch.colorGradient = data.colorGradient;
        }
        if (typeof data.textureMode === 'string') {
            patch.textureMode = data.textureMode;
        }
        if (typeof data.alignment === 'string') {
            patch.alignment = data.alignment;
        }
        if (Array.isArray(data.textureScale) && data.textureScale.length === 2) {
            patch.textureScale = data.textureScale;
        }
        if (typeof data.shadowCasting === 'boolean') {
            patch.shadowCasting = data.shadowCasting;
        }
        if (typeof data.generateLightingData === 'boolean') {
            patch.generateLightingData = data.generateLightingData;
        }
        if (typeof data.cornerVertices === 'number') {
            patch.cornerVertices = data.cornerVertices;
        }
        if (typeof data.endCapVertices === 'number') {
            patch.endCapVertices = data.endCapVertices;
        }
        if (typeof data.autodestruct === 'boolean') {
            patch.autodestruct = data.autodestruct;
        }

        this._applyConfig(patch);
    }

    /**
     * Advances the head index to drop expired points — O(k) where k =
     * number of expired points, with no array resizing or shifting.
     */
    private _pruneExpiredPoints(): void {
        const cutoffTime = this._elapsedTime - this._lifetime;

        while (this._pointCount > 0) {
            const headPoint = this._points[this._headIndex]!;
            if (headPoint.time < cutoffTime) {
                this._headIndex = (this._headIndex + 1) % this._capacity;
                this._pointCount--;
            } else {
                break;
            }
        }
    }

    /**
     * Writes a new point into the ring buffer at the tail position.
     * If the buffer is full the oldest point is silently overwritten
     * (head advances by one).
     */
    private _addPoint(x: number, y: number, z: number, time: number, width: number): void {
        const tailIndex = (this._headIndex + this._pointCount) % this._capacity;
        const point = this._points[tailIndex]!;
        point.position.x = x;
        point.position.y = y;
        point.position.z = z;
        point.time = time;
        point.width = width;

        if (this._pointCount < this._capacity) {
            this._pointCount++;
        } else {
            // Buffer full — overwrite oldest, advance head.
            this._headIndex = (this._headIndex + 1) % this._capacity;
        }
    }

    private _applyConfig(config: TrailRendererConfig): void {
        if (typeof config.lifetime === 'number') {
            this._lifetime = Math.max(0.001, config.lifetime);
        }
        if (typeof config.minVertexDistance === 'number') {
            this._minVertexDistance = Math.max(0.001, config.minVertexDistance);
        }
        if (typeof config.startWidth === 'number') {
            this._startWidth = Math.max(0, config.startWidth);
        }
        if (typeof config.endWidth === 'number') {
            this._endWidth = Math.max(0, config.endWidth);
        }
        if (config.widthCurve) {
            this._widthCurve = [...config.widthCurve];
        }
        if (config.colorGradient) {
            this._colorGradient = config.colorGradient.map((stop) => ({
                position: Math.max(0, Math.min(1, stop.position)),
                color: toVec4(stop.color),
            }));
        }
        if (config.textureMode) {
            this._textureMode = config.textureMode;
        }
        if (config.alignment) {
            this._alignment = config.alignment;
        }
        if (config.textureScale) {
            this._textureScaleX = config.textureScale[0];
            this._textureScaleY = config.textureScale[1];
        }
        if (typeof config.shadowCasting === 'boolean') {
            this._shadowCasting = config.shadowCasting;
        }
        if (typeof config.generateLightingData === 'boolean') {
            this._generateLightingData = config.generateLightingData;
        }
        if (typeof config.cornerVertices === 'number') {
            this._cornerVertices = Math.max(0, Math.floor(config.cornerVertices));
        }
        if (typeof config.endCapVertices === 'number') {
            this._endCapVertices = Math.max(0, Math.floor(config.endCapVertices));
        }
        if (typeof config.autodestruct === 'boolean') {
            this._autodestruct = config.autodestruct;
        }
    }
}
