// <auto-generated>
//     This file is generated. Do not edit by hand.
//
//     Generator: Axrone/web/packages/random/scripts/generate-seed-vectors.mjs
//     Source:    Axrone/web/packages/random/src/seed-utils.ts (hashSeedToState)
//     Commit:    git -C Axrone rev-parse HEAD
//     Generated: 2026-09-04
//
//     Regenerate:
//         node Axrone/web/packages/random/scripts/generate-seed-vectors.mjs > native/native/packages/Axrone.Random/tests/SeedHashVectors.g.cs
// </auto-generated>

namespace Axrone.Random.Tests;

using FluentAssertions;

/// <summary>
/// Machine-generated cross-language seed-hash vectors for <see cref="SeedHashing"/>: the
/// four 64-bit words the TypeScript <c>hashSeedToState</c> produces for a fixed corpus,
/// asserted against the native port so the two runtimes cannot silently diverge.
/// </summary>
/// <remarks>
/// <para>Regenerate with
/// <c>node Axrone/web/packages/random/scripts/generate-seed-vectors.mjs</c>; the CI drift
/// gate fails when this file is stale.</para>
/// <para>The integer-array vector is the one deliberate divergence: the reference
/// <c>Int32Array</c> branch shifts value <c>j</c> by <c>j * 32</c> inside a 64-bit word and
/// discards six of eight values, so <see cref="SeedHashing.HashIntsToWords"/> absorbs all
/// eight instead. This file locks the native output; the reference's broken output stays
/// pinned by
/// <c>SeedHashTests.HashIntsToWords_DoesNotFollowTheBrokenReferenceIntegerBranch</c>.</para>
/// </remarks>
public partial class SeedHashVectorTests
{
    [Theory]
    [InlineData("", 0x406EB0D8D886DF8BUL, 0x6DF7FF9A3C83EA9EUL, 0xD8A9BFF6FDD54AB6UL, 0xADC518956916D7FAUL)]
    [InlineData("a", 0x85223527BA7A6EA0UL, 0xC7ECC8DF08042A05UL, 0x44810A6898A554B9UL, 0x481F29B5F8D9B2F7UL)]
    [InlineData("level_01", 0xC213288CB3CF693CUL, 0x6826A0CA9E4020A4UL, 0x5ECCB909FB17B029UL, 0x4BB189A96539B1DAUL)]
    [InlineData("hello world", 0x486412697BFB1AEAUL, 0x8E04846CF1C7ADE9UL, 0x3739C1D885C213EAUL, 0x4D91A4643F59BC8BUL)]
    [InlineData("level_forest_cave_boss_room_wave_3_alpha", 0x4A097936E465F64CUL, 0x415720BDA3344D74UL, 0x2860E74D2A59DD7AUL, 0x5BFC7A60C2056466UL)]
    [InlineData("Hello, \u00E9\u00E0\u4E2D\u6587\U0001F600 end", 0x9C09443276A09A1AUL, 0x8DBACD830CB8C22BUL, 0x221CD3C72FDAA708UL, 0x768D7C8AAA6170EBUL)]
    [InlineData("0123456789abcdefghijklmnopqrstu", 0xF50D6AD79D382452UL, 0xD5BC7C8D82D634F8UL, 0x56499152B4BCF2F7UL, 0xC45E091D3B3CD052UL)]
    [InlineData("0123456789abcdefghijklmnopqrstuv", 0xB336DC3FB5A068ACUL, 0x6F4BF356FAC2AFCFUL, 0x89AC62AE5C952A7AUL, 0x50197BC862856A5DUL)]
    [InlineData("0123456789abcdefghijklmnopqrstuvw", 0x1B9AC144E55280D8UL, 0x0A66C16266173E73UL, 0x47F075A29CB8130EUL, 0x34394C0BE0DBD542UL)]
    [InlineData("level_forest_cave_boss_room_wave_3_alpha_and_a_long_tail_to_force_multiple_chunks", 0x227A6476EBCE0B5DUL, 0x25702A0E62A91EADUL, 0x62809861DD1E40EEUL, 0x46BCA6BD094F7866UL)]
    public void HashStringToWords_MatchesGeneratedVectors(
        string seed,
        ulong expected0,
        ulong expected1,
        ulong expected2,
        ulong expected3)
    {
        SeedHashing.HashStringToWords(seed).Should().Be((expected0, expected1, expected2, expected3));
    }

    [Theory]
    [InlineData(0x0000000000000000UL, 0xEAD40E1E37BABD54UL, 0x16B2FE219C70AB50UL, 0x8EB189D9A919D701UL, 0xB54FFC06F5523476UL)]
    [InlineData(0x000000000000002AUL, 0xBA2B2C53E723B288UL, 0x87F50A0B38747F7FUL, 0x4E0E9541CAFB3F38UL, 0x48BE3B8B30FF984BUL)]
    public void HashUInt64ToWords_MatchesGeneratedVectors(
        ulong seed,
        ulong expected0,
        ulong expected1,
        ulong expected2,
        ulong expected3)
    {
        SeedHashing.HashUInt64ToWords(seed).Should().Be((expected0, expected1, expected2, expected3));
    }

    [Theory]
    [InlineData(new int[] { 1, 2, 3, 4, 5, 6, 7, 8 }, 0x29FE304EA204430AUL, 0xD6EC505ADC25635CUL, 0x14D65FA8CD3BCB8DUL, 0x66F94BE13D1A9451UL)]
    public void HashIntsToWords_MatchesGeneratedVectors(
        int[] seed,
        ulong expected0,
        ulong expected1,
        ulong expected2,
        ulong expected3)
    {
        SeedHashing.HashIntsToWords(seed).Should().Be((expected0, expected1, expected2, expected3));
    }
}
