export const MAX_GLTF_SKIN_JOINTS = 128;

export const GLTF_SHADER_LIBRARIES = Object.freeze([
    {
        id: 'gltf.skinning',
        code: [
            'mat4 resolveSkinMatrix() {',
            '    if (!u_Skinning || u_SkinJointCount <= 0) {',
            '        return mat4(1.0);',
            '    }',
            '    mat4 skin = mat4(0.0);',
            '    skin += u_JointMatrices[int(a_Joints0.x)] * a_Weights0.x;',
            '    skin += u_JointMatrices[int(a_Joints0.y)] * a_Weights0.y;',
            '    skin += u_JointMatrices[int(a_Joints0.z)] * a_Weights0.z;',
            '    skin += u_JointMatrices[int(a_Joints0.w)] * a_Weights0.w;',
            '    return skin;',
            '}',
        ],
    },
    {
        id: 'gltf.uv',
        code: [
            'vec2 selectUV(int texCoord) {',
            '    return texCoord == 1 ? v_UV1 : v_UV0;',
            '}',
            '',
            'vec2 transformUV(vec2 uv, vec4 st, float rotation) {',
            '    vec2 scaled = uv * st.xy;',
            '    float c = cos(rotation);',
            '    float s = sin(rotation);',
            '    vec2 rotated = vec2(c * scaled.x - s * scaled.y, s * scaled.x + c * scaled.y);',
            '    return rotated + st.zw;',
            '}',
        ],
    },
    {
        id: 'gltf.color-space',
        code: [
            'vec3 linearToSrgb(vec3 color) {',
            '    vec3 clamped = clamp(color, vec3(0.0), vec3(1.0));',
            '    vec3 cutoff = step(vec3(0.0031308), clamped);',
            '    vec3 lower = clamped * 12.92;',
            '    vec3 higher = 1.055 * pow(clamped, vec3(1.0 / 2.4)) - 0.055;',
            '    return mix(lower, higher, cutoff);',
            '}',
            '',
            'vec3 srgbToLinear(vec3 color) {',
            '    vec3 clamped = clamp(color, vec3(0.0), vec3(1.0));',
            '    vec3 cutoff = step(vec3(0.04045), clamped);',
            '    vec3 lower = clamped / 12.92;',
            '    vec3 higher = pow((clamped + 0.055) / 1.055, vec3(2.4));',
            '    return mix(lower, higher, cutoff);',
            '}',
        ],
    },
    {
        id: 'gltf.fog',
        code: [
            '#ifdef FOG',
            'uniform int u_FogEnabled;',
            'uniform vec3 u_FogColor;',
            'uniform int u_FogMode;',
            'uniform float u_FogDensity;',
            'uniform vec2 u_FogStartEnd;',
            '',
            'vec3 applyFog(vec3 color, vec3 worldPos, vec3 cameraPos) {',
            '    if (u_FogEnabled == 0) return color;',
            '    float dist = length(worldPos - cameraPos);',
            '    float fogFactor = 0.0;',
            '    if (u_FogMode == 0) {',
            '        fogFactor = clamp((u_FogStartEnd.y - dist) / max(u_FogStartEnd.y - u_FogStartEnd.x, 0.001), 0.0, 1.0);',
            '    } else if (u_FogMode == 1) {',
            '        fogFactor = exp(-u_FogDensity * dist);',
            '    } else {',
            '        fogFactor = exp(-u_FogDensity * u_FogDensity * dist * dist);',
            '    }',
            '    return mix(u_FogColor, color, fogFactor);',
            '}',
            '#endif',
        ],
    },
    {
        id: 'gltf.pbr-lighting',
        code: [
            'const float PI = 3.14159265359;',
            'const float MIN_ROUGHNESS = 0.04;',
            'const float MAX_ROUGHNESS = 1.0;',
            '',
            'vec3 resolveNormal() {',
            '    vec3 normal = length(v_WorldNormal) > 0.0001 ? normalize(v_WorldNormal) : vec3(0.0, 0.0, 1.0);',
            '    if (_NormalTexture_TexCoord < 0 || length(v_WorldTangent.xyz) <= 0.0001) {',
            '        return normal;',
            '    }',
            '    vec2 uv = transformUV(selectUV(_NormalTexture_TexCoord), _NormalTexture_ST, _NormalTexture_Rotation);',
            '    vec3 tangentNormal = texture(_NormalTexture, uv).xyz * 2.0 - 1.0;',
            '    tangentNormal.xy *= _NormalTexture_Scale;',
            '    vec3 tangent = normalize(v_WorldTangent.xyz);',
            '    vec3 bitangent = normalize(cross(normal, tangent)) * (v_WorldTangent.w == 0.0 ? 1.0 : v_WorldTangent.w);',
            '    mat3 tbn = mat3(tangent, bitangent, normal);',
            '    return normalize(tbn * tangentNormal);',
            '}',
            '',
            'vec3 resolveClearcoatNormal(vec3 baseNormal) {',
            '    if (_ClearcoatNormalTexture_TexCoord < 0 || length(v_WorldTangent.xyz) <= 0.0001) {',
            '        return baseNormal;',
            '    }',
            '    vec2 uv = transformUV(selectUV(_ClearcoatNormalTexture_TexCoord), _ClearcoatNormalTexture_ST, _ClearcoatNormalTexture_Rotation);',
            '    vec3 tangentNormal = texture(_ClearcoatNormalTexture, uv).xyz * 2.0 - 1.0;',
            '    tangentNormal.xy *= _ClearcoatNormalTexture_Scale;',
            '    vec3 tangent = normalize(v_WorldTangent.xyz);',
            '    vec3 bitangent = normalize(cross(baseNormal, tangent)) * (v_WorldTangent.w == 0.0 ? 1.0 : v_WorldTangent.w);',
            '    mat3 tbn = mat3(tangent, bitangent, baseNormal);',
            '    return normalize(tbn * tangentNormal);',
            '}',
            '',
            'float rangeAttenuation(float distanceToLight, float range, float attenuationFactor) {',
            '    if (range <= 0.0) {',
            '        return 1.0;',
            '    }',
            '    float normalizedDist = distanceToLight / range;',
            '    return 1.0 / (1.0 + attenuationFactor * normalizedDist * normalizedDist);',
            '}',
            '',
            'float spotAttenuation(vec3 lightDir, vec3 spotDir, float innerConeCosine, float outerConeCosine) {',
            '    float cd = dot(normalize(-lightDir), normalize(spotDir));',
            '    return smoothstep(outerConeCosine, innerConeCosine, cd);',
            '}',
            '',
            'float distributionGgx(float NdotH, float roughness) {',
            '    float a = roughness * roughness;',
            '    float a2 = a * a;',
            '    float NdotH2 = NdotH * NdotH;',
            '    float denom = NdotH2 * (a2 - 1.0) + 1.0;',
            '    denom = PI * denom * denom;',
            '    return a2 / max(denom, 1e-7);',
            '}',
            '',
            'float geometrySchlickGgx(float NdotV, float roughness) {',
            '    float r = roughness + 1.0;',
            '    float k = (r * r) / 8.0;',
            '    return NdotV / (NdotV * (1.0 - k) + k);',
            '}',
            '',
            'float geometrySmith(float NdotV, float NdotL, float roughness) {',
            '    return geometrySchlickGgx(NdotV, roughness) * geometrySchlickGgx(NdotL, roughness);',
            '}',
            '',
            'vec3 fresnelSchlick(float cosTheta, vec3 F0) {',
            '    float t = 1.0 - cosTheta;',
            '    float t2 = t * t;',
            '    float t5 = t2 * t2 * t;',
            '    return F0 + (1.0 - F0) * t5;',
            '}',
            '',
            'vec3 fresnelSchlickRoughness(float cosTheta, vec3 F0, float roughness) {',
            '    float t = 1.0 - cosTheta;',
            '    float t2 = t * t;',
            '    float t5 = t2 * t2 * t;',
            '    return F0 + (max(vec3(1.0 - roughness), F0) - F0) * t5;',
            '}',
            '',
            'vec3 evaluateSpecularBrdf(vec3 N, vec3 V, vec3 L, float roughness, vec3 F0) {',
            '    vec3 H = normalize(V + L);',
            '    float NdotH = max(dot(N, H), 0.0);',
            '    float NdotV = max(dot(N, V), 0.001);',
            '    float NdotL = max(dot(N, L), 0.0);',
            '    float VdotH = max(dot(V, H), 0.0);',
            '    if (NdotL <= 0.0) {',
            '        return vec3(0.0);',
            '    }',
            '    float D = distributionGgx(NdotH, roughness);',
            '    float G = geometrySmith(NdotV, NdotL, roughness);',
            '    vec3 F = fresnelSchlick(VdotH, F0);',
            '    vec3 numerator = D * G * F;',
            '    float denominator = 4.0 * NdotV * NdotL + 0.001;',
            '    return numerator / denominator;',
            '}',
            '',
            'vec3 evaluateLight(vec3 normal, vec3 viewDir, vec3 albedo, float metallic, float roughness, vec3 lightDir, vec3 lightColor, float intensity) {',
            '    float NdotL = max(dot(normal, lightDir), 0.0);',
            '    if (NdotL <= 0.0) {',
            '        return vec3(0.0);',
            '    }',
            '    vec3 F0 = mix(vec3(0.04), albedo, metallic);',
            '    vec3 F = fresnelSchlick(max(dot(normalize(viewDir + lightDir), viewDir), 0.0), F0);',
            '    vec3 kS = F;',
            '    vec3 kD = (vec3(1.0) - kS) * (1.0 - metallic);',
            '    vec3 diffuse = kD * albedo / PI;',
            '    vec3 specular = evaluateSpecularBrdf(normal, viewDir, lightDir, roughness, F0);',
            '    vec3 kDenergy = (vec3(1.0) - F) * (1.0 - metallic);',
            '    vec3 specContrib = specular;',
            '    return (kDenergy * albedo / PI + specContrib) * lightColor * intensity * NdotL;',
            '}',
            '',
            'vec3 evaluateClearcoatLight(vec3 normal, vec3 viewDir, float clearcoat, float roughness, vec3 lightDir, vec3 lightColor, float intensity) {',
            '    if (clearcoat <= 0.0) {',
            '        return vec3(0.0);',
            '    }',
            '    float NdotL = max(dot(normal, lightDir), 0.0);',
            '    if (NdotL <= 0.0) {',
            '        return vec3(0.0);',
            '    }',
            '    vec3 H = normalize(viewDir + lightDir);',
            '    float NdotH = max(dot(normal, H), 0.0);',
            '    float NdotV = max(dot(normal, viewDir), 0.001);',
            '    float VdotH = max(dot(viewDir, H), 0.0);',
            '    float D = distributionGgx(NdotH, roughness);',
            '    float G = geometrySchlickGgx(NdotV, roughness) * geometrySchlickGgx(NdotL, roughness);',
            '    float F = 0.04 + 0.96 * pow(1.0 - VdotH, 5.0);',
            '    float spec = (D * G * F) / (4.0 * NdotV * NdotL + 0.001);',
            '    return vec3(spec * clearcoat) * lightColor * intensity * NdotL;',
            '}',
        ],
    },
    {
        id: 'gltf.ibl',
        code: [
            'vec3 evaluateIBLDiffuse(vec3 N, vec3 F0, float roughness, vec3 albedo, float metallic) {',
            '    vec3 F = fresnelSchlickRoughness(max(dot(N, normalize(u_CameraPosition - v_WorldPosition)), 0.0), F0, roughness);',
            '    vec3 kD = (1.0 - F) * (1.0 - metallic);',
            '    float hemiFactor = clamp(N.y * 0.5 + 0.5, 0.0, 1.0);',
            '    vec3 irradiance = mix(u_GroundLight, u_SkyLight, hemiFactor) + u_AmbientLight * 0.45;',
            '    return kD * irradiance * albedo;',
            '}',
            '',
            'vec3 evaluateIBLSpecular(vec3 N, vec3 V, vec3 F0, float roughness) {',
            '    vec3 R = reflect(-V, N);',
            '    vec3 F = fresnelSchlickRoughness(max(dot(N, V), 0.0), F0, roughness);',
            '    float hemiFactor = clamp(R.y * 0.5 + 0.5, 0.0, 1.0);',
            '    // Physically-correct IBL specular: prefiltered env color modulated by Fresnel and split-sum BRDF.',
            '    vec3 prefilteredColor = mix(u_GroundLight * 0.5, u_SkyLight, hemiFactor);',
            '    float NdotV = max(dot(N, V), 0.001);',
            '    float oneMinusNdotV = 1.0 - NdotV;',
            '    vec2 envBRDF = vec2(',
            '        clamp(pow(roughness, 0.6 + 0.2 * NdotV) * max(oneMinusNdotV, 0.0) * 1.7, 0.0, 1.0),',
            '        clamp(pow(roughness, 2.0 * NdotV) * oneMinusNdotV * 0.5 + 0.02, 0.0, 1.0)',
            '    );',
            '    return prefilteredColor * (F * envBRDF.x + envBRDF.y);',
            '}',
        ],
    },
    {
        id: 'gltf.shadow',
        code: [
            'float sampleShadowMap(vec2 uv, float compareDepth) {',
            '    return step(compareDepth, texture(u_ShadowMap, uv).r);',
            '}',
            '',
            'float shadowPcf2x2(vec2 baseUv, float compareDepth, vec2 texelSize) {',
            '    float shadow = 0.0;',
            '    shadow += step(compareDepth, texture(u_ShadowMap, baseUv + vec2(-0.5, -0.5) * texelSize).r);',
            '    shadow += step(compareDepth, texture(u_ShadowMap, baseUv + vec2( 0.5, -0.5) * texelSize).r);',
            '    shadow += step(compareDepth, texture(u_ShadowMap, baseUv + vec2(-0.5,  0.5) * texelSize).r);',
            '    shadow += step(compareDepth, texture(u_ShadowMap, baseUv + vec2( 0.5,  0.5) * texelSize).r);',
            '    return shadow * 0.25;',
            '}',
            '',
            'float shadowPcf3x3(vec2 baseUv, float compareDepth, vec2 texelSize) {',
            '    float shadow = 0.0;',
            '    for (int x = -1; x <= 1; x++) {',
            '        for (int y = -1; y <= 1; y++) {',
            '            vec2 offset = vec2(float(x), float(y)) * texelSize;',
            '            shadow += step(compareDepth, texture(u_ShadowMap, baseUv + offset).r);',
            '        }',
            '    }',
            '    return shadow / 9.0;',
            '}',
            '',
            'float resolveShadowFactor(vec3 worldPosition, vec3 worldNormal, vec3 lightDirection) {',
            '    if (u_ShadowEnabled <= 0) return 1.0;',
            '    int cascadeIndex = 0;',
            '    float viewDepth = length(u_CameraPosition - worldPosition);',
            '    for (int i = 0; i < 4; i++) {',
            '        if (viewDepth < u_ShadowCascadeSplits[i]) {',
            '            cascadeIndex = i;',
            '            break;',
            '        }',
            '        cascadeIndex = i;',
            '    }',
            '    if (cascadeIndex >= u_ShadowCascadeCount) return 1.0;',
            '    vec4 lightSpacePos = u_LightSpaceMatrices[cascadeIndex] * vec4(worldPosition, 1.0);',
            '    vec3 projCoords = lightSpacePos.xyz / lightSpacePos.w;',
            '    projCoords = projCoords * 0.5 + 0.5;',
            '    if (projCoords.x < 0.0 || projCoords.x > 1.0 || projCoords.y < 0.0 || projCoords.y > 1.0) return 1.0;',
            '    if (projCoords.z > 1.0) return 1.0;',
            '    float NdotL = max(dot(worldNormal, lightDirection), 0.0);',
            '    float bias = max(u_ShadowBias * (1.0 - NdotL), u_ShadowBias * 0.1);',
            '    vec3 biasedPos = worldPosition + worldNormal * u_ShadowNormalBias;',
            '    vec4 biasedLightPos = u_LightSpaceMatrices[cascadeIndex] * vec4(biasedPos, 1.0);',
            '    vec3 biasedProj = biasedLightPos.xyz / biasedLightPos.w * 0.5 + 0.5;',
            '    float currentDepth = biasedProj.z - bias;',
            '    vec2 texelSize = vec2(1.0 / 2048.0);',
            '    return shadowPcf3x3(biasedProj.xy, currentDepth, texelSize);',
            '}',
        ],
    },
    {
        id: 'gltf.advanced-shading',
        code: [
            'vec3 evaluateAnisotropicSpecular(vec3 N, vec3 V, vec3 L, float roughness, float anisotropy, vec3 tangent, vec3 bitangent, vec3 F0) {',
            '    float at = max(roughness * (1.0 + anisotropy), 0.001);',
            '    float ab = max(roughness * (1.0 - anisotropy), 0.001);',
            '    vec3 H = normalize(V + L);',
            '    float NdotH = max(dot(N, H), 0.0);',
            '    float TdotH = dot(tangent, H);',
            '    float BdotH = dot(bitangent, H);',
            '    float NdotV = max(dot(N, V), 0.001);',
            '    float NdotL = max(dot(N, L), 0.0);',
            '    if (NdotL <= 0.0) return vec3(0.0);',
            '    float a2 = at * ab;',
            '    vec3 v = vec3(ab * TdotH, at * BdotH, a2 * NdotH);',
            '    float v2 = dot(v, v);',
            '    float w2 = a2 / max(v2, 1e-7);',
            '    float D = a2 * w2 * w2 * (1.0 / PI);',
            '    float G = geometrySmith(NdotV, NdotL, roughness);',
            '    float VdotH = max(dot(V, H), 0.0);',
            '    vec3 F = fresnelSchlick(VdotH, F0);',
            '    return (D * G * F) / (4.0 * NdotV * NdotL + 0.001);',
            '}',
            '',
            'vec3 evaluateSheen(vec3 N, vec3 V, vec3 L, vec3 sheenColor, float sheenRoughness) {',
            '    vec3 H = normalize(V + L);',
            '    float NdotL = max(dot(N, L), 0.0);',
            '    float NdotH = max(dot(N, H), 0.0);',
            '    float NdotV = max(dot(N, V), 0.001);',
            '    if (NdotL <= 0.0) return vec3(0.0);',
            '    float roughnessSq = max(sheenRoughness * sheenRoughness, 1e-4);',
            '    float invRoughnessSq = 1.0 / roughnessSq;',
            '    float cos2h = NdotH * NdotH;',
            '    float sin2h = max(1.0 - cos2h, 0.0);',
            '    float D = (2.0 + invRoughnessSq) * pow(sin2h, invRoughnessSq * 0.5) / (2.0 * PI);',
            '    float VdotH = max(dot(V, H), 0.0);',
            '    float F = VdotH * exp2((-5.55473 * VdotH - 6.98316) * VdotH);',
            '    return sheenColor * D * F * NdotL;',
            '}',
            '',
            'vec3 evaluateSubsurface(vec3 albedo, vec3 N, vec3 V, vec3 L, vec3 lightColor, float intensity, float thickness, vec3 subsurfaceColor) {',
            '    vec3 H = normalize(V + L);',
            '    float VdotH = max(dot(V, H), 0.0);',
            '    float NdotL = max(dot(N, L), 0.0);',
            '    float scatter = pow(clamp(1.0 - VdotH + 0.4, 0.0, 1.0), 3.0) * 0.5;',
            '    vec3 sssColor = mix(albedo, subsurfaceColor, thickness);',
            '    return sssColor * (scatter + NdotL * 0.2) * lightColor * intensity;',
            '}',
            '',
            'vec3 evaluateTransmission(vec3 albedo, vec3 N, vec3 V, vec3 L, float ior, float thickness) {',
            '    vec3 refracted = refract(-V, N, 1.0 / max(ior, 1.001));',
            '    float NdotL = max(dot(N, L), 0.0);',
            '    float VdotL = max(dot(V, -L), 0.0);',
            '    float transmission = pow(clamp(VdotL, 0.0, 1.0), 4.0);',
            '    float absorption = exp(-thickness * 2.0);',
            '    return albedo * transmission * absorption * (1.0 - NdotL * 0.3);',
            '}',
            '',
            'vec3 evaluateIridescence(float cosTheta, float iridescence, float ior, float thickness) {',
            '    float x = cosTheta;',
            '    float x2 = x * x;',
            '    float x3 = x2 * x;',
            '    float x4 = x3 * x;',
            '    float x5 = x4 * x;',
            '    float theta = acos(clamp(cosTheta, -1.0, 1.0));',
            '    float sinTheta2 = sin(theta) * sin(theta);',
            '    float cosTheta2 = cosTheta * cosTheta;',
            '    float eta2 = ior * ior;',
            '    float t0 = sqrt(eta2 - sinTheta2);',
            '    float t1 = t0 * cosTheta;',
            '    float t2 = (2.0 * PI * thickness * t0) / 550.0;',
            '    vec3 wavelengths = vec3(650.0, 550.0, 450.0);',
            '    vec3 phase = 2.0 * PI * thickness * t0 / wavelengths;',
            '    vec3 reflectance = vec3(',
            '        0.5 * (1.0 + cos(phase.x)),',
            '        0.5 * (1.0 + cos(phase.y)),',
            '        0.5 * (1.0 + cos(phase.z))',
            '    );',
            '    float f0 = pow((ior - 1.0) / (ior + 1.0), 2.0);',
            '    reflectance *= f0 * 2.0;',
            '    return mix(vec3(1.0), reflectance, iridescence);',
            '}',
        ],
    },
] as const);
