import type { RenderShaderEffectDefinition } from '@axrone/scene-runtime';
import { GLTF_SHADER_LIBRARIES } from './gltf-shader-libraries';
import {
    GLTF_LIGHTING_UNIFORMS,
    HIDDEN_INSPECTOR,
    MAX_GLTF_DIRECTIONAL_LIGHTS,
    MAX_GLTF_POINT_LIGHTS,
    MAX_GLTF_SPOT_LIGHTS,
    createLightingProperties,
    createSharedAlphaProperties,
    createSharedObjectProperties,
    createSurfaceTextureProperties,
} from './gltf-shader-properties';

const GLTF_SHADER_PBR_ID = 'gltf/pbr';

export const createGltfPbrShaderEffect = (id: string): RenderShaderEffectDefinition => ({
    format: 'axrone.shader/effect',
    version: 1,
    id,
    attributes: [
        { name: 'a_Position', type: 'vec3', location: 0 },
        { name: 'a_Normal', type: 'vec3', location: 1 },
        { name: 'a_UV0', type: 'vec2', location: 2 },
        { name: 'a_Tangent', type: 'vec4', location: 4 },
        { name: 'a_UV1', type: 'vec2', location: 5 },
        { name: 'a_Joints0', type: 'uvec4', location: 9 },
        { name: 'a_Weights0', type: 'vec4', location: 10 },
    ],
    varyings: [
        { name: 'v_UV0', type: 'vec2' },
        { name: 'v_UV1', type: 'vec2' },
        { name: 'v_WorldPosition', type: 'vec3' },
        { name: 'v_WorldNormal', type: 'vec3' },
        { name: 'v_WorldTangent', type: 'vec4' },
    ],
    properties: [
        ...createSharedObjectProperties(),
        {
            name: 'u_ReceiveLighting',
            type: 'bool',
            stages: ['fragment'],
            scope: 'system',
            inspector: HIDDEN_INSPECTOR,
        },
        {
            name: 'u_ShadowEnabled',
            type: 'int',
            stages: ['fragment'],
            scope: 'frame',
            defaultValue: 0,
            inspector: HIDDEN_INSPECTOR,
        },
        {
            name: 'u_ShadowCascadeCount',
            type: 'int',
            stages: ['fragment'],
            scope: 'frame',
            defaultValue: 0,
            inspector: HIDDEN_INSPECTOR,
        },
        {
            name: 'u_ShadowBias',
            type: 'float',
            stages: ['fragment'],
            scope: 'frame',
            defaultValue: 0.0015,
            inspector: HIDDEN_INSPECTOR,
        },
        {
            name: 'u_ShadowNormalBias',
            type: 'float',
            stages: ['fragment'],
            scope: 'frame',
            defaultValue: 0.25,
            inspector: HIDDEN_INSPECTOR,
        },
        {
            name: 'u_ShadowCascadeSplits',
            type: 'float',
            arrayLength: 4,
            stages: ['fragment'],
            scope: 'frame',
            inspector: HIDDEN_INSPECTOR,
        },
        {
            name: 'u_LightSpaceMatrices',
            type: 'mat4',
            arrayLength: 4,
            stages: ['fragment'],
            scope: 'frame',
            inspector: HIDDEN_INSPECTOR,
        },
        {
            name: 'u_ShadowMap',
            type: 'sampler2D',
            stages: ['fragment'],
            scope: 'system',
            inspector: HIDDEN_INSPECTOR,
        },
        ...createLightingProperties(),
        {
            name: 'u_CameraPosition',
            type: 'vec3',
            stages: ['fragment'],
            scope: 'camera',
            inspector: HIDDEN_INSPECTOR,
        },
        {
            name: '_BaseColorFactor',
            type: 'vec4',
            stages: ['fragment'],
            scope: 'material',
            defaultValue: [1, 1, 1, 1],
            inspector: {
                label: 'Base Color',
                group: 'Surface',
                control: 'color',
            },
        },
        ...createSurfaceTextureProperties('_BaseColorTexture', 'Base Color Map', 'Maps'),
        {
            name: '_MetallicFactor',
            type: 'float',
            stages: ['fragment'],
            scope: 'material',
            defaultValue: 1,
            inspector: {
                label: 'Metallic',
                group: 'Surface',
                control: 'slider',
                min: 0,
                max: 1,
                step: 0.01,
            },
        },
        {
            name: '_RoughnessFactor',
            type: 'float',
            stages: ['fragment'],
            scope: 'material',
            defaultValue: 1,
            inspector: {
                label: 'Roughness',
                group: 'Surface',
                control: 'slider',
                min: 0,
                max: 1,
                step: 0.01,
            },
        },
        ...createSurfaceTextureProperties(
            '_MetallicRoughnessTexture',
            'Metallic Roughness Map',
            'Maps'
        ),
        {
            name: '_ClearcoatFactor',
            type: 'float',
            stages: ['fragment'],
            scope: 'material',
            defaultValue: 0,
            inspector: {
                label: 'Clear Coat',
                group: 'Clear Coat',
                control: 'slider',
                min: 0,
                max: 1,
                step: 0.01,
            },
        },
        {
            name: '_ClearcoatRoughnessFactor',
            type: 'float',
            stages: ['fragment'],
            scope: 'material',
            defaultValue: 0,
            inspector: {
                label: 'Clear Coat Roughness',
                group: 'Clear Coat',
                control: 'slider',
                min: 0,
                max: 1,
                step: 0.01,
            },
        },
        ...createSurfaceTextureProperties('_ClearcoatTexture', 'Clear Coat Map', 'Clear Coat'),
        ...createSurfaceTextureProperties(
            '_ClearcoatRoughnessTexture',
            'Clear Coat Roughness Map',
            'Clear Coat'
        ),
        ...createSurfaceTextureProperties('_ClearcoatNormalTexture', 'Clear Coat Normal Map', 'Clear Coat', {
            scale: {
                label: 'Clear Coat Normal Scale',
                min: 0,
                max: 2,
                step: 0.01,
                defaultValue: 1,
            },
        }),
        ...createSurfaceTextureProperties('_NormalTexture', 'Normal Map', 'Maps', {
            scale: {
                label: 'Normal Scale',
                min: 0,
                max: 2,
                step: 0.01,
                defaultValue: 1,
            },
        }),
        ...createSurfaceTextureProperties('_OcclusionTexture', 'Occlusion Map', 'Maps', {
            strength: {
                label: 'Occlusion Strength',
                min: 0,
                max: 1,
                step: 0.01,
                defaultValue: 1,
            },
        }),
        {
            name: '_EmissiveFactor',
            type: 'vec3',
            stages: ['fragment'],
            scope: 'material',
            defaultValue: [0, 0, 0],
            inspector: {
                label: 'Emissive',
                group: 'Emission',
                control: 'color',
            },
        },
        ...createSurfaceTextureProperties('_EmissiveTexture', 'Emissive Map', 'Emission'),
        {
            name: '_SheenFactor',
            type: 'float',
            stages: ['fragment'],
            scope: 'material',
            defaultValue: 0,
            inspector: {
                label: 'Sheen Intensity',
                group: 'Sheen',
                control: 'slider',
                min: 0,
                max: 1,
                step: 0.01,
            },
        },
        {
            name: '_SheenColorFactor',
            type: 'vec3',
            stages: ['fragment'],
            scope: 'material',
            defaultValue: [0, 0, 0],
            inspector: {
                label: 'Sheen Color',
                group: 'Sheen',
                control: 'color',
            },
        },
        {
            name: '_SheenRoughnessFactor',
            type: 'float',
            stages: ['fragment'],
            scope: 'material',
            defaultValue: 0.5,
            inspector: {
                label: 'Sheen Roughness',
                group: 'Sheen',
                control: 'slider',
                min: 0,
                max: 1,
                step: 0.01,
            },
        },
        {
            name: '_AnisotropyFactor',
            type: 'float',
            stages: ['fragment'],
            scope: 'material',
            defaultValue: 0,
            inspector: {
                label: 'Anisotropy',
                group: 'Anisotropy',
                control: 'slider',
                min: -1,
                max: 1,
                step: 0.01,
            },
        },
        {
            name: '_AnisotropyRotation',
            type: 'float',
            stages: ['fragment'],
            scope: 'material',
            defaultValue: 0,
            inspector: {
                label: 'Anisotropy Rotation',
                group: 'Anisotropy',
                control: 'slider',
                min: 0,
                max: 6.283,
                step: 0.01,
            },
        },
        {
            name: '_SubsurfaceFactor',
            type: 'float',
            stages: ['fragment'],
            scope: 'material',
            defaultValue: 0,
            inspector: {
                label: 'Subsurface',
                group: 'Subsurface',
                control: 'slider',
                min: 0,
                max: 1,
                step: 0.01,
            },
        },
        {
            name: '_SubsurfaceColorFactor',
            type: 'vec3',
            stages: ['fragment'],
            scope: 'material',
            defaultValue: [1, 0.8, 0.6],
            inspector: {
                label: 'Subsurface Color',
                group: 'Subsurface',
                control: 'color',
            },
        },
        {
            name: '_SubsurfaceThickness',
            type: 'float',
            stages: ['fragment'],
            scope: 'material',
            defaultValue: 1,
            inspector: {
                label: 'Subsurface Thickness',
                group: 'Subsurface',
                control: 'slider',
                min: 0,
                max: 5,
                step: 0.01,
            },
        },
        {
            name: '_TransmissionFactor',
            type: 'float',
            stages: ['fragment'],
            scope: 'material',
            defaultValue: 0,
            inspector: {
                label: 'Transmission',
                group: 'Transmission',
                control: 'slider',
                min: 0,
                max: 1,
                step: 0.01,
            },
        },
        {
            name: '_IorFactor',
            type: 'float',
            stages: ['fragment'],
            scope: 'material',
            defaultValue: 1.5,
            inspector: {
                label: 'Index of Refraction',
                group: 'Transmission',
                control: 'slider',
                min: 1,
                max: 3,
                step: 0.01,
            },
        },
        {
            name: '_ThicknessFactor',
            type: 'float',
            stages: ['fragment'],
            scope: 'material',
            defaultValue: 0,
            inspector: {
                label: 'Thickness',
                group: 'Transmission',
                control: 'slider',
                min: 0,
                max: 5,
                step: 0.01,
            },
        },
        {
            name: '_IridescenceFactor',
            type: 'float',
            stages: ['fragment'],
            scope: 'material',
            defaultValue: 0,
            inspector: {
                label: 'Iridescence',
                group: 'Iridescence',
                control: 'slider',
                min: 0,
                max: 1,
                step: 0.01,
            },
        },
        {
            name: '_IridescenceIor',
            type: 'float',
            stages: ['fragment'],
            scope: 'material',
            defaultValue: 1.3,
            inspector: {
                label: 'Iridescence IOR',
                group: 'Iridescence',
                control: 'slider',
                min: 1,
                max: 3,
                step: 0.01,
            },
        },
        {
            name: '_IridescenceThickness',
            type: 'float',
            stages: ['fragment'],
            scope: 'material',
            defaultValue: 400,
            inspector: {
                label: 'Iridescence Thickness',
                group: 'Iridescence',
                control: 'slider',
                min: 100,
                max: 1000,
                step: 1,
            },
        },
        ...createSharedAlphaProperties(),
        {
            name: 'u_FogEnabled',
            type: 'int',
            stages: ['fragment'],
            scope: 'system',
            inspector: HIDDEN_INSPECTOR,
        },
        {
            name: 'u_FogColor',
            type: 'vec3',
            stages: ['fragment'],
            scope: 'system',
            inspector: HIDDEN_INSPECTOR,
        },
        {
            name: 'u_FogMode',
            type: 'int',
            stages: ['fragment'],
            scope: 'system',
            inspector: HIDDEN_INSPECTOR,
        },
        {
            name: 'u_FogDensity',
            type: 'float',
            stages: ['fragment'],
            scope: 'system',
            defaultValue: 0.015,
            inspector: HIDDEN_INSPECTOR,
        },
        {
            name: 'u_FogStartEnd',
            type: 'vec2',
            stages: ['fragment'],
            scope: 'system',
            defaultValue: [0, 300],
            inspector: HIDDEN_INSPECTOR,
        },
    ],
    libraries: GLTF_SHADER_LIBRARIES,
    vertex: {
        includes: ['gltf.skinning'],
        main: [
            'v_UV0 = a_UV0;',
            'v_UV1 = a_UV1;',
            'mat4 skin = resolveSkinMatrix();',
            'vec4 localPosition = vec4(a_Position, 1.0);',
            'vec3 localNormal = a_Normal;',
            'vec3 localTangent = a_Tangent.xyz;',
            'if (u_Skinning && u_SkinJointCount > 0) {',
            '    localPosition = skin * localPosition;',
            '    localNormal = mat3(skin) * localNormal;',
            '    localTangent = mat3(skin) * localTangent;',
            '}',
            'vec4 worldPosition = u_Model * localPosition;',
            'v_WorldPosition = worldPosition.xyz;',
            'v_WorldNormal = normalize(transpose(inverse(mat3(u_Model))) * localNormal);',
            'v_WorldTangent = vec4(normalize(transpose(inverse(mat3(u_Model))) * localTangent), a_Tangent.w);',
            'gl_Position = u_Projection * u_View * worldPosition;',
        ],
    },
    fragment: {
        precision: 'highp',
        outputs: [{ name: 'o_Color', type: 'vec4' }],
        includes: ['gltf.uv', 'gltf.pbr-lighting', 'gltf.ibl', 'gltf.shadow', 'gltf.advanced-shading', 'gltf.color-space', 'gltf.fog'],
        main: [
            'vec4 baseColor = _BaseColorFactor;',
            'if (_BaseColorTexture_TexCoord >= 0) {',
            '    vec2 uv = transformUV(selectUV(_BaseColorTexture_TexCoord), _BaseColorTexture_ST, _BaseColorTexture_Rotation);',
            '    baseColor *= texture(_BaseColorTexture, uv);',
            '}',
            'int alphaMode = int(_AlphaMode + 0.5);',
            'if (alphaMode == 1 && baseColor.a < _AlphaCutoff) {',
            '    discard;',
            '}',
            '',
            'vec3 normal = resolveNormal();',
            'float clearcoat = clamp(_ClearcoatFactor, 0.0, 1.0);',
            'if (_ClearcoatTexture_TexCoord >= 0) {',
            '    vec2 uv = transformUV(selectUV(_ClearcoatTexture_TexCoord), _ClearcoatTexture_ST, _ClearcoatTexture_Rotation);',
            '    clearcoat *= texture(_ClearcoatTexture, uv).r;',
            '}',
            'float clearcoatRoughness = clamp(_ClearcoatRoughnessFactor, 0.0, 1.0);',
            'if (_ClearcoatRoughnessTexture_TexCoord >= 0) {',
            '    vec2 uv = transformUV(selectUV(_ClearcoatRoughnessTexture_TexCoord), _ClearcoatRoughnessTexture_ST, _ClearcoatRoughnessTexture_Rotation);',
            '    clearcoatRoughness *= texture(_ClearcoatRoughnessTexture, uv).g;',
            '}',
            'clearcoatRoughness = clamp(clearcoatRoughness, 0.04, 1.0);',
            'vec3 clearcoatNormal = clearcoat > 0.0 ? resolveClearcoatNormal(normal) : normal;',
            'float baseLayerEnergy = 1.0 - (clearcoat * 0.25);',
            'vec3 viewDir = normalize(u_CameraPosition - v_WorldPosition);',
            'vec2 mrUv = transformUV(selectUV(max(_MetallicRoughnessTexture_TexCoord, 0)), _MetallicRoughnessTexture_ST, _MetallicRoughnessTexture_Rotation);',
            'vec4 mrSample = _MetallicRoughnessTexture_TexCoord >= 0 ? texture(_MetallicRoughnessTexture, mrUv) : vec4(1.0);',
            'float roughness = clamp(_RoughnessFactor * mrSample.g, 0.04, 1.0);',
            'float metallic = clamp(_MetallicFactor * mrSample.b, 0.0, 1.0);',
            'vec3 F0 = mix(vec3(0.04), baseColor.rgb, metallic);',
            '',
            'float anisotropy = clamp(_AnisotropyFactor, -1.0, 1.0);',
            'vec3 tangent = normalize(v_WorldTangent.xyz);',
            'vec3 bitangent = normalize(cross(normal, tangent)) * (v_WorldTangent.w == 0.0 ? 1.0 : v_WorldTangent.w);',
            'if (_AnisotropyRotation > 0.001) {',
            '    float c = cos(_AnisotropyRotation);',
            '    float s = sin(_AnisotropyRotation);',
            '    vec3 rotTangent = c * tangent + s * bitangent;',
            '    bitangent = -s * tangent + c * bitangent;',
            '    tangent = rotTangent;',
            '}',
            '',
            'float sheenFactor = clamp(_SheenFactor, 0.0, 1.0);',
            'vec3 sheenColor = _SheenColorFactor * sheenFactor;',
            'float sheenRoughness = clamp(_SheenRoughnessFactor, 0.04, 1.0);',
            '',
            'float subsurfaceFactor = clamp(_SubsurfaceFactor, 0.0, 1.0);',
            'vec3 subsurfaceColor = _SubsurfaceColorFactor;',
            'float subsurfaceThickness = max(_SubsurfaceThickness, 0.0);',
            '',
            'float transmissionFactor = clamp(_TransmissionFactor, 0.0, 1.0);',
            'float ior = max(_IorFactor, 1.001);',
            'float thickness = max(_ThicknessFactor, 0.0);',
            '',
            'float iridescenceFactor = clamp(_IridescenceFactor, 0.0, 1.0);',
            'float iridescenceIor = max(_IridescenceIor, 1.0);',
            'float iridescenceThickness = clamp(_IridescenceThickness, 100.0, 1000.0);',
            '',
            'vec3 lighting = vec3(0.0);',
            '',
            'if (u_ReceiveLighting) {',
            `    for (int index = 0; index < ${MAX_GLTF_DIRECTIONAL_LIGHTS}; index += 1) {`,
            `        if (index >= ${GLTF_LIGHTING_UNIFORMS.directionalLightCount}) {`,
            '            break;',
            '        }',
            `        vec3 lightDir = normalize(-${GLTF_LIGHTING_UNIFORMS.directionalLightDirection}[index]);`,
            `        vec3 lightColor = ${GLTF_LIGHTING_UNIFORMS.directionalLightColor}[index];`,
            `        float intensity = ${GLTF_LIGHTING_UNIFORMS.directionalLightIntensity}[index];`,
            '        vec3 diffuse = baseColor.rgb * (1.0 - metallic) / PI;',
            '        vec3 spec;',
            '        if (abs(anisotropy) > 0.001) {',
            '            spec = evaluateAnisotropicSpecular(normal, viewDir, lightDir, roughness, anisotropy, tangent, bitangent, F0);',
            '        } else {',
            '            spec = evaluateSpecularBrdf(normal, viewDir, lightDir, roughness, F0);',
            '        }',
            '        float NdotL = max(dot(normal, lightDir), 0.0);',
            '        vec3 F = fresnelSchlick(max(dot(normalize(viewDir + lightDir), viewDir), 0.0), F0);',
            '        vec3 kD = (vec3(1.0) - F) * (1.0 - metallic);',
            '        vec3 directLight = (kD * diffuse + spec) * lightColor * intensity * NdotL;',
            '        if (sheenFactor > 0.001) {',
            '            directLight += evaluateSheen(normal, viewDir, lightDir, sheenColor, sheenRoughness) * lightColor * intensity;',
            '        }',
            '        if (subsurfaceFactor > 0.001) {',
            '            directLight += evaluateSubsurface(baseColor.rgb, normal, viewDir, lightDir, lightColor, intensity, subsurfaceThickness * subsurfaceFactor, subsurfaceColor) * subsurfaceFactor;',
            '        }',
            '        if (transmissionFactor > 0.001) {',
            '            directLight += evaluateTransmission(baseColor.rgb, normal, viewDir, lightDir, ior, thickness) * lightColor * intensity * transmissionFactor;',
            '        }',
            '        vec3 directionalClearcoat = evaluateClearcoatLight(clearcoatNormal, viewDir, clearcoat, clearcoatRoughness, lightDir, lightColor, intensity);',
            '        float shadowFactor = resolveShadowFactor(v_WorldPosition, normal, lightDir);',
            '        lighting += (directLight * baseLayerEnergy + directionalClearcoat) * shadowFactor;',
            '    }',
            '    vec3 iblDiffuse = evaluateIBLDiffuse(normal, F0, roughness, baseColor.rgb, metallic);',
            '    vec3 iblSpecular = evaluateIBLSpecular(normal, viewDir, F0, roughness);',
            '    vec3 ibl = iblDiffuse + iblSpecular;',
            '    if (iridescenceFactor > 0.001) {',
            '        float NdotV = max(dot(normal, viewDir), 0.001);',
            '        vec3 iridescenceFresnel = evaluateIridescence(NdotV, iridescenceFactor, iridescenceIor, iridescenceThickness);',
            '        ibl *= iridescenceFresnel;',
            '    }',
            '    lighting += ibl * baseLayerEnergy;',
            `    for (int index = 0; index < ${MAX_GLTF_POINT_LIGHTS}; index += 1) {`,
            `        if (index >= ${GLTF_LIGHTING_UNIFORMS.pointLightCount}) {`,
            '            break;',
            '        }',
            `        vec3 toLight = ${GLTF_LIGHTING_UNIFORMS.pointLightPosition}[index] - v_WorldPosition;`,
            '        float distanceToLight = length(toLight);',
            '        vec3 lightDir = distanceToLight > 0.0 ? toLight / distanceToLight : vec3(0.0, 1.0, 0.0);',
            `        float attenuation = rangeAttenuation(distanceToLight, ${GLTF_LIGHTING_UNIFORMS.pointLightRange}[index], ${GLTF_LIGHTING_UNIFORMS.pointLightAttenuation}[index]);`,
            `        vec3 lightColor = ${GLTF_LIGHTING_UNIFORMS.pointLightColor}[index];`,
            `        float intensity = ${GLTF_LIGHTING_UNIFORMS.pointLightIntensity}[index] * attenuation;`,
            '        vec3 diffuse = baseColor.rgb * (1.0 - metallic) / PI;',
            '        vec3 spec;',
            '        if (abs(anisotropy) > 0.001) {',
            '            spec = evaluateAnisotropicSpecular(normal, viewDir, lightDir, roughness, anisotropy, tangent, bitangent, F0);',
            '        } else {',
            '            spec = evaluateSpecularBrdf(normal, viewDir, lightDir, roughness, F0);',
            '        }',
            '        float NdotL = max(dot(normal, lightDir), 0.0);',
            '        vec3 F = fresnelSchlick(max(dot(normalize(viewDir + lightDir), viewDir), 0.0), F0);',
            '        vec3 kD = (vec3(1.0) - F) * (1.0 - metallic);',
            '        vec3 pointLightContrib = (kD * diffuse + spec) * lightColor * intensity * NdotL;',
            '        if (sheenFactor > 0.001) {',
            '            pointLightContrib += evaluateSheen(normal, viewDir, lightDir, sheenColor, sheenRoughness) * lightColor * intensity;',
            '        }',
            '        if (subsurfaceFactor > 0.001) {',
            '            pointLightContrib += evaluateSubsurface(baseColor.rgb, normal, viewDir, lightDir, lightColor, intensity, subsurfaceThickness * subsurfaceFactor, subsurfaceColor) * subsurfaceFactor;',
            '        }',
            '        if (transmissionFactor > 0.001) {',
            '            pointLightContrib += evaluateTransmission(baseColor.rgb, normal, viewDir, lightDir, ior, thickness) * lightColor * intensity * transmissionFactor;',
            '        }',
            `        vec3 pointClearcoat = evaluateClearcoatLight(clearcoatNormal, viewDir, clearcoat, clearcoatRoughness, lightDir, lightColor, intensity);`,
            '        lighting += pointLightContrib * baseLayerEnergy + pointClearcoat;',
            '    }',
            `    for (int index = 0; index < ${MAX_GLTF_SPOT_LIGHTS}; index += 1) {`,
            `        if (index >= ${GLTF_LIGHTING_UNIFORMS.spotLightCount}) {`,
            '            break;',
            '        }',
            `        vec3 toLight = ${GLTF_LIGHTING_UNIFORMS.spotLightPosition}[index] - v_WorldPosition;`,
            '        float distanceToLight = length(toLight);',
            '        vec3 lightDir = distanceToLight > 0.0 ? toLight / distanceToLight : vec3(0.0, 1.0, 0.0);',
            `        float attenuation = rangeAttenuation(distanceToLight, ${GLTF_LIGHTING_UNIFORMS.spotLightRange}[index], 2.0);`,
            `        attenuation *= spotAttenuation(lightDir, ${GLTF_LIGHTING_UNIFORMS.spotLightDirection}[index], ${GLTF_LIGHTING_UNIFORMS.spotLightInnerConeCosine}[index], ${GLTF_LIGHTING_UNIFORMS.spotLightOuterConeCosine}[index]);`,
            `        vec3 lightColor = ${GLTF_LIGHTING_UNIFORMS.spotLightColor}[index];`,
            `        float intensity = ${GLTF_LIGHTING_UNIFORMS.spotLightIntensity}[index] * attenuation;`,
            '        vec3 diffuse = baseColor.rgb * (1.0 - metallic) / PI;',
            '        vec3 spec;',
            '        if (abs(anisotropy) > 0.001) {',
            '            spec = evaluateAnisotropicSpecular(normal, viewDir, lightDir, roughness, anisotropy, tangent, bitangent, F0);',
            '        } else {',
            '            spec = evaluateSpecularBrdf(normal, viewDir, lightDir, roughness, F0);',
            '        }',
            '        float NdotL = max(dot(normal, lightDir), 0.0);',
            '        vec3 F = fresnelSchlick(max(dot(normalize(viewDir + lightDir), viewDir), 0.0), F0);',
            '        vec3 kD = (vec3(1.0) - F) * (1.0 - metallic);',
            '        vec3 spotLightContrib = (kD * diffuse + spec) * lightColor * intensity * NdotL;',
            '        if (sheenFactor > 0.001) {',
            '            spotLightContrib += evaluateSheen(normal, viewDir, lightDir, sheenColor, sheenRoughness) * lightColor * intensity;',
            '        }',
            '        if (subsurfaceFactor > 0.001) {',
            '            spotLightContrib += evaluateSubsurface(baseColor.rgb, normal, viewDir, lightDir, lightColor, intensity, subsurfaceThickness * subsurfaceFactor, subsurfaceColor) * subsurfaceFactor;',
            '        }',
            '        if (transmissionFactor > 0.001) {',
            '            spotLightContrib += evaluateTransmission(baseColor.rgb, normal, viewDir, lightDir, ior, thickness) * lightColor * intensity * transmissionFactor;',
            '        }',
            `        vec3 spotClearcoat = evaluateClearcoatLight(clearcoatNormal, viewDir, clearcoat, clearcoatRoughness, lightDir, lightColor, intensity);`,
            '        lighting += spotLightContrib * baseLayerEnergy + spotClearcoat;',
            '    }',
            '} else {',
            '    vec3 iblDiffuse = evaluateIBLDiffuse(normal, F0, roughness, baseColor.rgb, metallic);',
            '    vec3 iblSpecular = evaluateIBLSpecular(normal, viewDir, F0, roughness);',
            '    lighting = (iblDiffuse + iblSpecular) * baseLayerEnergy;',
            '}',
            '',
            'if (_OcclusionTexture_TexCoord >= 0) {',
            '    vec2 uv = transformUV(selectUV(_OcclusionTexture_TexCoord), _OcclusionTexture_ST, _OcclusionTexture_Rotation);',
            '    float occlusion = texture(_OcclusionTexture, uv).r;',
            '    lighting *= mix(1.0, occlusion, clamp(_OcclusionTexture_Strength, 0.0, 1.0));',
            '}',
            '',
            'vec3 emissive = _EmissiveFactor;',
            'if (_EmissiveTexture_TexCoord >= 0) {',
            '    vec2 uv = transformUV(selectUV(_EmissiveTexture_TexCoord), _EmissiveTexture_ST, _EmissiveTexture_Rotation);',
            '    emissive *= texture(_EmissiveTexture, uv).rgb;',
            '}',
            '',
            'float alpha = alphaMode == 2 ? baseColor.a : 1.0;',
            'vec3 finalColor = lighting + emissive;',
            '#ifdef FOG',
            'finalColor = applyFog(finalColor, v_WorldPosition, u_CameraPosition);',
            '#endif',
            'o_Color = vec4(linearToSrgb(finalColor), alpha);',
        ],
    },
    renderState: {
        depthTest: true,
        cull: true,
        blend: false,
    },
});

export const GLTF_PBR_SHADER_EFFECT = createGltfPbrShaderEffect(GLTF_SHADER_PBR_ID);
